name: memorae
description: "Projecto universitario."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.18.0
  drift_sqflite: ^2.0.1
  sqflite: ^2.3.3+1           # (explícito; lo usa drift_sqflite)
  path_provider: ^2.1.4       # para obtener la ruta del archivo .db


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  drift_dev: ^2.18.0
  build_runner: ^2.4.9


flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  image_path: "assets/icon/memorae.png" # ruta de tu ícono
  color: "#FFFFFF"                    # fondo
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 24 # opcional, asegura compatibilidad


flutter_native_splash:
  color: "#FFFFFF"                    # fondo
  image: assets/splash/memorae_splash.png   # logo del splash (puede ser distinto al icono)
  android_12:
    color: "#FFFFFF"
    image: assets/splash/memorae_splash_android12.png